package mentoring2;

public class UsingTryCatch {

	public static void main(String[] args) {
		
//		Execption Handling
//		Try catch
//		Try this if not correct then catch it
		
		try {
			int num2 =6;
			int num3 =0;
			int division =num2/num3;
			System.out.println("division result is :" +division);
			
		}catch (Exception e) {
//			e.printStackTrace();
			
			System.out.println("This is Arithmetic exception ");
		}
		
		
		
		
		
	}

}
